language: groovy
jdk:
- oraclejdk8
sudo: false
branches:
  only:
  - master
  - develop
before_install:
 - wget -q https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/ala_common.sh
 - chmod +x ala_common.sh
 - source ./ala_common.sh
 - ala_travis_grails_setup_env
script:
 - ala_travis_grails_build
env:
  global:
  - secure: anZyiypNFsFqqG4i6qpr3BTD9/yOYSTeW+MIkWKDR68VuY+IAxLCLdDYFUg+lNQbIpiZy8OoLigdgY0AxYw+/IliT/hxBjI64vDEQTkwHI6syb/TAnEdyvWIRtXxj7LqCcRrco1qhNcKD+eYUb4a3/9lRCh3ADhXIh8pFA+1N+s=
  - secure: BBwEK7eVHFHyE+Hrg/T2dK670jvhvAY56P8KNYslr2V1puD8f5m122TfIbpbltBFJ/oF+xXl3LCVWCPE7wuY1PP14TmLJY0zqARQGsj35c4H0I85+OGVvwp8McX57rEfSnxUYxlVBAlj1xq0U6nq8Bm5Gmk0m/vKEGdvSxvTRGA=
