#!/bin/sh

#######################################################
#
# Add here the commands to be excuted after the package
# has been removed
#

if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
fi
if [ -f /usr/share/dbconfig-common/dpkg/postrm.mysql ]; then
    . /usr/share/dbconfig-common/dpkg/postrm.mysql
    dbc_go ala-collectory "$@"
fi

#DEBHELPER#

echo ala-collectory removed.
